#!/usr/bin/env python
# coding: utf-8

# In[ ]:


You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


# In[8]:


#Accepted but very bad run time and memory
def findTheDifference(s, t):
    tlst = list(t)
    slst = list(s)
    for letter in tlst:
        if letter not in slst:
            return letter
        else:
            slst.remove(letter)
            


# In[9]:


s = "abcd"
t = "abcde"
findTheDifference(s, t)

